set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")

set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -mfpu=neon")

set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)

set (CMAKE_CXX_STANDARD 17)

set(CMAKE_FIND_ROOT_PATH /usr/arm-linux-gnueabihf/)

set(THREADS_PTHREAD_ARG /usr/arm-linux-gnueabihf/)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
